- name: ec2 instance launch
  hosts: localhost
  connection: local
  tasks:
          - name: ec2 launch
            ec2:
                instance_type: t2.micro
                key_name: website
                image: ami-0443305dabd4be2bc
                region: us-east-2
                vpc_subnet_id: subnet-5ee7c812
                wait: yes
                group: ansible
                count: 1
                assign_public_ip: yes

