- name: Running the Nginx using tags
  hosts: client
  become: yes
  tasks:
          - name: Installing of nginx
            yum:
                    
                    name: nginx
                    state: installed
          - name: Start the nginx service
            service:
                    name: nginx
                    state: restarted
                    enabled: yes 
            tags: restart     
          - name: Copy the index.html file 
            copy:
                    src: index.html
                    dest: /usr/share/nginx/html/
          - name: Start the firewall
            service: 
                    name: firewalld
                    state: restarted
                    enabled: yes
            tags: restart        
          - name: Allow the nginx in firewalld           
            firewalld:
                    service: http
                    permanent: yes
                    state: enabled
                    immediate: yes
